void po_obv_lepton_pair_azimuth_pair()
{
//=========Macro generated from canvas: c1/ 
//=========  (Mon Feb 25 08:51:53 2019) by ROOT version6.08/06
   TCanvas *c1 = new TCanvas("c1", " ",0,0,1000,700);
   gStyle->SetOptStat(0);
   c1->Range(-0.6974359,-48913.71,3.405128,222829.1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(0);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.17);
   c1->SetRightMargin(0.05);
   c1->SetTopMargin(0.07);
   c1->SetBottomMargin(0.18);
   c1->SetFrameFillStyle(0);
   c1->SetFrameLineWidth(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderSize(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameLineWidth(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderSize(0);
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *_stack_1 = new TH1F("_stack_1","",320,0,3.2);
   _stack_1->SetMinimum(0);
   _stack_1->SetMaximum(203807.1);
   _stack_1->SetDirectory(0);
   _stack_1->SetStats(0);
   _stack_1->SetLineStyle(0);
   _stack_1->SetMarkerStyle(7);
   _stack_1->GetXaxis()->SetTitle("M_{Z}");
   _stack_1->GetXaxis()->SetNdivisions(505);
   _stack_1->GetXaxis()->SetLabelFont(42);
   _stack_1->GetXaxis()->SetLabelOffset(0.01);
   _stack_1->GetXaxis()->SetLabelSize(0.07);
   _stack_1->GetXaxis()->SetTitleSize(0.07);
   _stack_1->GetXaxis()->SetTitleOffset(1.2);
   _stack_1->GetXaxis()->SetTitleFont(42);
   _stack_1->GetYaxis()->SetTitle("Events");
   _stack_1->GetYaxis()->SetNdivisions(505);
   _stack_1->GetYaxis()->SetLabelFont(42);
   _stack_1->GetYaxis()->SetLabelOffset(0.01);
   _stack_1->GetYaxis()->SetLabelSize(0.07);
   _stack_1->GetYaxis()->SetTitleSize(0.07);
   _stack_1->GetYaxis()->SetTitleOffset(1.2);
   _stack_1->GetYaxis()->SetTitleFont(42);
   _stack_1->GetZaxis()->SetNdivisions(505);
   _stack_1->GetZaxis()->SetLabelFont(42);
   _stack_1->GetZaxis()->SetLabelOffset(0.01);
   _stack_1->GetZaxis()->SetLabelSize(0.06);
   _stack_1->GetZaxis()->SetTitleSize(0.07);
   _stack_1->GetZaxis()->SetTitleFont(42);
   ->SetHistogram(_stack_1);
   
   
   TH1F *po_obv_lepton_pair_azimuth_pair0__1 = new TH1F("po_obv_lepton_pair_azimuth_pair0__1","M_{Z}Events",320,0,3.2);
   po_obv_lepton_pair_azimuth_pair0__1->SetBinContent(1,194102);
   po_obv_lepton_pair_azimuth_pair0__1->SetEntries(194102);
   po_obv_lepton_pair_azimuth_pair0__1->SetStats(0);
   po_obv_lepton_pair_azimuth_pair0__1->SetLineWidth(4);
   po_obv_lepton_pair_azimuth_pair0__1->SetMarkerStyle(7);
   po_obv_lepton_pair_azimuth_pair0__1->GetXaxis()->SetNdivisions(505);
   po_obv_lepton_pair_azimuth_pair0__1->GetXaxis()->SetLabelFont(42);
   po_obv_lepton_pair_azimuth_pair0__1->GetXaxis()->SetLabelOffset(0.01);
   po_obv_lepton_pair_azimuth_pair0__1->GetXaxis()->SetLabelSize(0.07);
   po_obv_lepton_pair_azimuth_pair0__1->GetXaxis()->SetTitleSize(0.07);
   po_obv_lepton_pair_azimuth_pair0__1->GetXaxis()->SetTitleOffset(1.2);
   po_obv_lepton_pair_azimuth_pair0__1->GetXaxis()->SetTitleFont(42);
   po_obv_lepton_pair_azimuth_pair0__1->GetYaxis()->SetNdivisions(505);
   po_obv_lepton_pair_azimuth_pair0__1->GetYaxis()->SetLabelFont(42);
   po_obv_lepton_pair_azimuth_pair0__1->GetYaxis()->SetLabelOffset(0.01);
   po_obv_lepton_pair_azimuth_pair0__1->GetYaxis()->SetLabelSize(0.07);
   po_obv_lepton_pair_azimuth_pair0__1->GetYaxis()->SetTitleSize(0.07);
   po_obv_lepton_pair_azimuth_pair0__1->GetYaxis()->SetTitleOffset(1.2);
   po_obv_lepton_pair_azimuth_pair0__1->GetYaxis()->SetTitleFont(42);
   po_obv_lepton_pair_azimuth_pair0__1->GetZaxis()->SetNdivisions(505);
   po_obv_lepton_pair_azimuth_pair0__1->GetZaxis()->SetLabelFont(42);
   po_obv_lepton_pair_azimuth_pair0__1->GetZaxis()->SetLabelOffset(0.01);
   po_obv_lepton_pair_azimuth_pair0__1->GetZaxis()->SetLabelSize(0.06);
   po_obv_lepton_pair_azimuth_pair0__1->GetZaxis()->SetTitleSize(0.07);
   po_obv_lepton_pair_azimuth_pair0__1->GetZaxis()->SetTitleFont(42);
   ->Add(po_obv_lepton_pair_azimuth_pair0,"");
   
   TH1F *py_obv_lepton_pair_azimuth_pair1__2 = new TH1F("py_obv_lepton_pair_azimuth_pair1__2","M_{Z}Events",320,0,3.2);
   py_obv_lepton_pair_azimuth_pair1__2->SetBinContent(1,194102);
   py_obv_lepton_pair_azimuth_pair1__2->SetEntries(194102);
   py_obv_lepton_pair_azimuth_pair1__2->SetStats(0);
   py_obv_lepton_pair_azimuth_pair1__2->SetLineColor(2);
   py_obv_lepton_pair_azimuth_pair1__2->SetLineStyle(2);
   py_obv_lepton_pair_azimuth_pair1__2->SetLineWidth(4);
   py_obv_lepton_pair_azimuth_pair1__2->SetMarkerStyle(7);
   py_obv_lepton_pair_azimuth_pair1__2->GetXaxis()->SetNdivisions(505);
   py_obv_lepton_pair_azimuth_pair1__2->GetXaxis()->SetLabelFont(42);
   py_obv_lepton_pair_azimuth_pair1__2->GetXaxis()->SetLabelOffset(0.01);
   py_obv_lepton_pair_azimuth_pair1__2->GetXaxis()->SetLabelSize(0.07);
   py_obv_lepton_pair_azimuth_pair1__2->GetXaxis()->SetTitleSize(0.07);
   py_obv_lepton_pair_azimuth_pair1__2->GetXaxis()->SetTitleOffset(1.2);
   py_obv_lepton_pair_azimuth_pair1__2->GetXaxis()->SetTitleFont(42);
   py_obv_lepton_pair_azimuth_pair1__2->GetYaxis()->SetNdivisions(505);
   py_obv_lepton_pair_azimuth_pair1__2->GetYaxis()->SetLabelFont(42);
   py_obv_lepton_pair_azimuth_pair1__2->GetYaxis()->SetLabelOffset(0.01);
   py_obv_lepton_pair_azimuth_pair1__2->GetYaxis()->SetLabelSize(0.07);
   py_obv_lepton_pair_azimuth_pair1__2->GetYaxis()->SetTitleSize(0.07);
   py_obv_lepton_pair_azimuth_pair1__2->GetYaxis()->SetTitleOffset(1.2);
   py_obv_lepton_pair_azimuth_pair1__2->GetYaxis()->SetTitleFont(42);
   py_obv_lepton_pair_azimuth_pair1__2->GetZaxis()->SetNdivisions(505);
   py_obv_lepton_pair_azimuth_pair1__2->GetZaxis()->SetLabelFont(42);
   py_obv_lepton_pair_azimuth_pair1__2->GetZaxis()->SetLabelOffset(0.01);
   py_obv_lepton_pair_azimuth_pair1__2->GetZaxis()->SetLabelSize(0.06);
   py_obv_lepton_pair_azimuth_pair1__2->GetZaxis()->SetTitleSize(0.07);
   py_obv_lepton_pair_azimuth_pair1__2->GetZaxis()->SetTitleFont(42);
   ->Add(py_obv_lepton_pair_azimuth_pair1,"");
   
   TH1F *po_cmuon_obv_lepton_pair_azimuth_pair2__3 = new TH1F("po_cmuon_obv_lepton_pair_azimuth_pair2__3","M_{Z}Events",320,0,3.2);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->SetBinContent(1,194102);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->SetEntries(194102);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->SetStats(0);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->SetLineColor(4);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->SetLineStyle(3);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->SetLineWidth(4);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->SetMarkerStyle(7);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetXaxis()->SetNdivisions(505);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetXaxis()->SetLabelFont(42);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetXaxis()->SetLabelOffset(0.01);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetXaxis()->SetLabelSize(0.07);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetXaxis()->SetTitleSize(0.07);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetXaxis()->SetTitleOffset(1.2);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetXaxis()->SetTitleFont(42);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetYaxis()->SetNdivisions(505);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetYaxis()->SetLabelFont(42);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetYaxis()->SetLabelOffset(0.01);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetYaxis()->SetLabelSize(0.07);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetYaxis()->SetTitleSize(0.07);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetYaxis()->SetTitleOffset(1.2);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetYaxis()->SetTitleFont(42);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetZaxis()->SetNdivisions(505);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetZaxis()->SetLabelFont(42);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetZaxis()->SetLabelOffset(0.01);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetZaxis()->SetLabelSize(0.06);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetZaxis()->SetTitleSize(0.07);
   po_cmuon_obv_lepton_pair_azimuth_pair2__3->GetZaxis()->SetTitleFont(42);
   ->Add(po_cmuon_obv_lepton_pair_azimuth_pair2,"");
   ->Draw("nostack");
   
   TLegend *leg = new TLegend(0.2,0.6,0.4,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("po_obv_lepton_pair_azimuth_pair0","PFO","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("py_obv_lepton_pair_azimuth_pair1","PY","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(2);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("po_cmuon_obv_lepton_pair_azimuth_pair2","cheat muon","l");
   entry->SetLineColor(4);
   entry->SetLineStyle(3);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
